### ISSUE TITLE
CRIAR FUNÇÃO ALTERNATIVA - DRAG AND DROP

### ISSUE THREAD

**Issue by LucasBrbs** [mbcalisto/smellicious#7]
# Checklist

- [x] Accessibility representation da table view
- [x] Colocar cada celula com a respectiva imagem e label
- [x] chamar função de drop quando clicado
- [x] chamar sheet e resposta de haptics quando segurar no botao

**Comment by paulohgs** [comment]
- Realizar a deseleção da essência já colocada
- Escolher palavras a descrição da ação dos botões das essências
- Se já selecionada, quando clicada novamente desselecionar

**Comment by paulohgs** [comment]
A task de chamar sheet vai virar uma nova atividade dentro do projeto.
